---
services:

  rabbitmq:
    # Here we deliberately use a recent RabbitMQ
    # to ensure the application is compatible with it.
    # This version may differ from the version used in production
    image: rabbitmq:4.0.5-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_NODENAME: rabbit@localhost
      RABBITMQ_DEFAULT_USER: es
      RABBITMQ_DEFAULT_PASS: cheddar1963
      RABBITMQ_ENABLED_PLUGINS_FILE: /config/enabled_plugins
    ports:
    - '4369:4369'
    - '5672:5672'
    - '15672:15672'
    - '25672:25672'
    volumes:
    - type: bind
      source: ./rabbitmq-enabled-plugins
      target: /config
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 10

  memcached:
    image: memcached:1.6.38-alpine3.21
    container_name: memcached
    environment:
      MEMCACHED_MAX_ITEM_SIZE: 36
      MEMCACHED_MAX_CONNECTIONS: 1
      MEMCACHED_MEMORY_LIMIT: 64
    ports:
    - '11211:11211'

  es:
    build:
      context: .
    image: informaticsmatters/squonk2-fastapi-ws-event-stream:latest
    container_name: es
    environment:
      ESS_AMPQ_URL: 'amqp://es:cheddar1963@rabbitmq:5672'
      ESS_INGRESS_LOCATION: 'localhost:8080'
      ESS_INGRESS_SECURE: 'no'
      ESS_MEMCACHED_LOCATION: memcached
    ports:
    # Public (Websocket)
    - '8080:8080'
    # Internal (API)
    - '8081:8081'
    depends_on:
      rabbitmq:
        condition: service_healthy
      memcached:
        condition: service_started
