[project]
name = "squonk2-fastapi-ws-event-stream"
version = "3.0.0"
description = "A Squonk2 Python FastAPI AS EvenStream Service"
authors = [{ name = "Alan Christie", email = "alan.christie@matildapeak.com" }]
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    # Locked versions (for now)
    "fastapi>=0.116.1,<0.117.0",
    "uvicorn[standard]>=0.35.0,<0.36.0",
    "python-dateutil==2.9.0",
    # Flexible versions
    "pymemcache>=4.0.0,<5.0.0",
    "pydantic>=2.11.7,<3.0.0",
    "rstream>=0.30.0,<0.31.0",
    "shortuuid>=1.0.13,<2.0.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.0.0,<5.0.0",
    "pylint>=3.3.4,<4.0.0",
    "simple-websocket>=1.1.0,<2.0.0",
    "websockets>=15.0.0,<16.0.0",
    "httpie>=3.2.4,<4.0.0",
    "isort>=6.0.0,<7.0.0",
    "black>=25.1.0,<26.0.0",
    "mypy>=1.15.0,<2.0.0",
    "im-protobuf>=7.1.0,<8.0.0",
]

[tool.uv]
# There is nothing to build or publish here -
# the application is delivered as a container image,
# so uv must not try to install this project into its own environment.
package = false

[tool.commitizen]
name = "cz_customize"
version_provider = "pep621"
prerelease_offset = 1

[tool.commitizen.customize]
schema_pattern = "(build|bump|chore|ci|dev|docs|feat|fix|perf|refactor|remove|style|test):(\\s.*)"
commit_parser = "^(?P<change_type>build|bump|chore|ci|dev|docs|feat|fix|perf|refactor|remove|style|test):\\s(?P<message>.*)?"
# By excluding 'bump', 'ci', 'dev', and 'docs' from
# 'change_type_map', 'change_type_order' and 'changelog_pattern'
# we omit the corresponding commit comments from the CHANGELOG.
# The order of types in the CHANGELOG is dictated by the type_order
change_type_map = {"feat" = "New Features", "fix" = "Bug Fixes", "perf" = "Performance Improvements", "refactor" = "Refactoring", "chore" = "General Improvements", "remove" = "Removed", "style" = "Stylistic Changes", "test" = "Testing", "build" = "Build"}
change_type_order = ["BREAKING CHANGE", "New Features", "Bug Fixes", "Performance Improvements", "Refactoring", "General Improvements", "Removed", "Stylistic Changes", "Testing", "Build"]
changelog_pattern = "^(build|chore|feat|fix|perf|refactor|remove|style|test)"
