---

# Ingress class
ess_ingress_class: nginx
# The base of each ClusterIssuer class.
# Were we expect issuers to be something like 'letsencrypt-nginx'
# and typically have 'letsencrypt-nginx-staging'
# and 'letsencrypt-nginx-production'
ess_cert_manager_issuer_base: letsencrypt-{{ ess_ingress_class }}
# SSL certificate issuer?
# One of 'production', 'staging' or blank (for no SSL).
ess_cert_issuer:

# memcached image tag
ess_memcached_tag: 1.6.38-alpine3.21
ess_memcached_memory_limit: 200m
# memcached resources
ess_memcached_cpu_request: 100m
ess_memcached_cpu_limit:
ess_memcached_mem_request: 256Mi
ess_memcached_mem_limit: 256Mi

# Environment
# Number of connections
ess_memcached_max_connections: 4
# Max item size - we use uuid4() strings
ess_memcached_max_item_size: 36
ess_message_stats_interval: 800

ess_priority_class:
ess_api_termination_grace_period_seconds: 30
